name: dotfiles

services:
  playground:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        DOTFILES_CONTEXT: .
    volumes:
      - type: bind
        source: ${PWD}
        target: /home/ubuntu/dotfiles
    environment:
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
      EDITOR: ${EDITOR}
    tty: true
