# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

# https://sheldon.cli.rs/Examples.html#deferred-loading-of-plugins-in-zsh
[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"

# local files
# [plugins.local]
# local = "~/.config/zsh"
# use = ["*.zsh"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ['source']

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ['source']

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ['defer']

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ['defer']

[plugins.rust-zsh-completions]
github = "ryutok/rust-zsh-completions"
apply = ['defer']

[plugins.eza]
inline = "alias ls='eza --icons'"

[plugins.bat]
inline = "alias cat=bat"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'
