[tools]
'aqua:github/copilot-cli' = 'latest'
'aqua:tealdeer-rs/tealdeer' = 'latest'
"npm:@github/copilot-language-server" = "latest"
"github:Feel-ix-343/markdown-oxide" = "latest"

bat = 'latest'
btop = 'latest'
difftastic = 'latest'
dust = 'latest'
eza = 'latest'
fd = 'latest'
fzf = 'latest'
ghq = 'latest'
github-cli = 'latest'
lazygit = 'latest'
node = 'lts'
ripgrep = 'latest'
sd = 'latest'
starship = 'latest'
tree-sitter = 'latest'
yazi = 'latest'
zellij = 'latest'
zoxide = 'latest'

[settings]
plugin_autoupdate_last_check_duration = '1 week'
