[tools]
bat = 'latest'
btop = 'latest'
copilot = 'latest'
difftastic = 'latest'
direnv = 'latest'
fzf = 'latest'
lazygit = 'latest'
dust = 'latest'
eza = 'latest'
fd = 'latest'
github-cli = 'latest'
ripgrep = 'latest'
sd = 'latest'
starship = 'latest'
tealdeer = 'latest'
tree-sitter = 'latest'
uv = 'latest'
yazi = 'latest'
zellij = 'latest'
zoxide = 'latest'

[settings]
plugin_autoupdate_last_check_duration = '1 week'
