[helpers]

[default]
depends = [
    "clang-format",
    "git",
    "helix",
    "lazygit",
    "mise",
    "starship",
    "wezterm",
    "nvim-config",
]

[clang-format.files]
"files/clang-format" = "~/.clang-format"

[git.files]
"files/gitconfig" = "~/.gitconfig"
"files/config/git" = "~/.config/git"

[helix.files]
"files/config/helix" = "~/.config/helix"

[lazygit.files]
"files/config/lazygit" = "~/.config/lazygit"

[mise.files]
"files/config/mise" = "~/.config/mise"

[starship.files]
"files/config/starship.toml" = "~/.config/starship.toml"

[wezterm.files]
"files/config/wezterm" = "~/.config/wezterm"

# Files in `nvim-config` submodule
[nvim-config]
depends = ["neovide", "neovim"]

[neovide.files]
"nvim-config/neovide" = "~/.config/neovide"

[neovim.files]
"nvim-config/nvim" = "~/.config/nvim"

[settings]
default_target_type = "symbolic"
