[helpers]

[default]
depends = [
    "clang-format",
    "fish",
    "ghostty",
    "git",
    "helix",
    "lazygit",
    "mise",
    "neovide",
    "neovim",
    "wezterm",
    "zellij",
    "zsh",
]

[clang-format.files]
"files/clang-format" = "~/.clang-format"

[fish.files]
"files/config/fish" = "~/.config/fish"

[ghostty.files]
"files/config/ghostty" = "~/.config/ghostty"

[git.files]
"files/gitconfig" = "~/.gitconfig"
"files/config/git" = "~/.config/git"

[helix.files]
"files/config/helix" = "~/.config/helix"

[lazygit.files]
"files/config/lazygit" = "~/.config/lazygit"

[mise.files]
"files/config/mise" = "~/.config/mise"

[neovide.files]
"nvim-config/neovide" = "~/.config/neovide"

[neovim.files]
"nvim-config/nvim" = "~/.config/nvim"

[wezterm.files]
"files/config/wezterm" = "~/.config/wezterm"

[zellij.files]
"files/config/zellij" = "~/.config/zellij"

[zsh.files]
"files/zshrc" = "~/.zshrc"
"files/config/starship.toml" = "~/.config/starship.toml"
"files/config/sheldon" = "~/.config/sheldon"
"files/config/zsh" = "~/.config/zsh"

[settings]
default_target_type = "symbolic"
