[latex.files]
"files/override/windows/latexmkrc" = "~/.latexmkrc"
"files/override/windows/indentconfig.yaml" = "~/.indentconfig.yaml"
"files/override/windows/AppData/Local/latexindent/default.yaml" = "~/AppData/Local/latexindent/default.yaml"
"files/override/windows/AppData/Roaming/tex-fmt/tex-fmt.toml" = "~/AppData/Roaming/tex-fmt/tex-fmt.toml"

[nushell.files]
"files/override/windows/AppData/Roaming/nushell" = "~/AppData/Roaming/nushell"

[powershell.files]
"files/override/windows/Documents/PowerShell/Microsoft.PowerShell_profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"files/override/windows/AppData/Roaming/powershell" = "~/AppData/Roaming/powershell"

[vcxsrv.files]
"files/override/windows/config.xlaunch" = "~/.config.xlaunch"

[wsl.files]
"files/override/windows/wslconfig" = "~/.wslconfig"

# override
[helix]
depends = ["helix"]

[helix.files]
"files/config/helix" = "~/AppData/Roaming/helix"

# override
[lazygit]
depends = ["lazygit"]

[lazygit.files]
"files/config/lazygit" = "~/AppData/Local/lazygit"

# override
[neovide]
depends = ["neovide"]

[neovide.files]
"nvim-config/neovide" = "~/AppData/Roaming/neovide"

# override
[neovim]
depends = ["neovim"]

[neovim.files]
"nvim-config/nvim" = "~/AppData/Local/nvim"
