[windows]
depends = ["latex", "nushell", "powershell", "vcxsrv", "wsl", "override"]

[latex.files]
"files/override/windows/latexmkrc" = "~/.latexmkrc"
"files/override/windows/indentconfig.yaml" = "~/.indentconfig.yaml"
"files/override/windows/AppData/Local/latexindent/default.yaml" = "~/AppData/Local/latexindent/default.yaml"
"files/override/windows/AppData/Roaming/tex-fmt/tex-fmt.toml" = "~/AppData/Roaming/tex-fmt/tex-fmt.toml"

[nushell.files]
"files/override/windows/AppData/Roaming/nushell" = "~/AppData/Roaming/nushell"

[powershell.files]
"files/override/windows/Documents/PowerShell/Microsoft.PowerShell_profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"files/override/windows/AppData/Roaming/powershell" = "~/AppData/Roaming/powershell"

[vcxsrv.files]
"files/override/windows/config.xlaunch" = "~/.config.xlaunch"

[wsl.files]
"files/override/windows/wslconfig" = "~/.wslconfig"

# ---- Override default packages ----
[override]
depends = ["helix", "lazygit", "nvim-config"]

[helix.files]
"files/config/helix" = "~/AppData/Roaming/helix"

[lazygit.files]
"files/config/lazygit" = "~/AppData/Local/lazygit"

[neovide.files] # `nvim-config` dependant
"nvim-config/neovide" = "~/AppData/Roaming/neovide"

[neovim.files] # `nvim-config` dependant
"nvim-config/nvim" = "~/AppData/Local/nvim"
